### ISSUE TITLE
Other Basis Sets

### ISSUE THREAD

**Issue by cortner** [mfherbst/DFTK.jl#54]
This may be far outside your interest so feel free to just close this but have you considered allowing other basis sets, eg atomic orbitals, ...

**Comment by antoine-levitt** [comment]
Atomic orbitals use significantly different techniques, so having both in a single project would just make things more complicated without significant code sharing (plus there's pyscf which is apparently pretty good). Finite element/differences might be interesting and could probably have a nice unified codebase, but no immediate plans on my end.

**Comment by cortner** [comment]
ok, then I'll just close this for now

**Comment by mfherbst** [comment]
I'm not sure I fully agree with @antoine-levitt. I think it could be interestingto  make sense to add atomic basis sets at some point

I'd be interested in adding atomic-orbital type basis sets at some point, but that's definitely talking quite long-term and only once

**Comment by antoine-levitt** [comment]
The point is that the structure of the code right now (SCF plus application of the hamiltonian) is more suited to "large" basis sets (PW/FE/FD) than "small" basis sets (eg gaussians), where the tradeoffs are different. I think the relevant question is which current functions would be shared with another basis set. I can see a lot of functions that would be usable in an FE/FD implementation (SCF, iterative diagonalization, pseudos, hamiltonian application), but barely any that would be in a gaussian implementation (essentially just lattice and kpoint handling). Putting two mostly orthogonal codes in a single framework just leads to bloat IMO (because then you're naturally led to build "fake abstractions" that are convoluted ways to abstract on two completely different things). But then I guess the situation is not that clear-cut with other types of basis sets, like wavelets of sturmians or whatever, and we'll probably want at some point to have some kind of interface with localized functions (eg to compute projected DoS, Wannier functions, etc.) so there might be some merit to the idea. Might be interesting to see eg what GPAW does here.

**Comment by cortner** [comment]
So maybe a better idea would be to have an AbstractDFT package that provides a unified interface to various concepts that DFT packages would implement.

**Comment by mfherbst** [comment]
@antoine-levitt With these arguments I can agree. An additional aspects, where I expect benefit in code-sharing would be the SCF fixed-point solvers. As you know I worked on abstracting this a while ago, but it definitely became too convoluted in my previous attempts. I still feel it can be done better.

@cortner I like the idea of trying to generalise to an abstract interface. That way common structure and code can be expressed and specific details kept in the individual implementations, keeping them simple and without bloat. I'm not sure `AbstractDFT` is the right name as other SCF-like approaches (e.g. Hartree-Fock) are basically the same ... let's keep that in mind for the future, however.

**Comment by antoine-levitt** [comment]
Re fixed-point, I definitely agree about that, but the place to do that is in NLsolve I think

Re abstract interface: we'll see if and when we have multiple "user" codes (julip-like) calling multiple "producer" codes (dftk-like)

**Comment by mfherbst** [comment]
Yes NLsolve sounds better.

For sure, I agree :smile: ... but as you know ... sometimes I like to envision the distant future.
